* Generelt om tælleugen

** Tælleuge formål

Formålet er ikke en generel måling af borgerpresset, men en konkret måling
af eksterne ind- og udgående henvendelser, så effektiviteten af kanalstrategien
kan måles.
I forlængelse af ovenstående skal det gøres klart hvilke målsætninger, der er
ved tælleugen, og om disse målsætninger er modstridende eller komplimentære.
Hvis målsætningen er dokumentation af effekten af kanastrategien, og samtidig
nogle lokale parametre til måling af internt ressourceforbrug, skal dette
tydeliggøres.

*** Diagram over prioriterede kanaltyper

Lav et diagram over kanaltyper, efter hvilke der koster mest efter [[http://www.kl.dk/Fagomrader/Administration-og-digitalisering/e2015/Kanalpriser/][Kanalpriser]].
- Hvorfor?
  - De indledende kanaler skulle gerne filtrere så mange henvendelser fra som muligt
  - Om det så er almindelige henvendelser eller fejlhenvendelser, er det ideen at borgeren
    skal kunne informationssøge selvstændigt på de indledende kanaler


*** Siden sidst

Hvad har Køge for at højne selvbetjeningsgraden siden sidste tælleuge?

** Tælleuge argumenter

Både lokation og varighed bør dokumenteres, så kommunen kan fremvise, det egentlige
ressourceforbrug i form af differentieret varighed af henvendelser. Især, hvordan
nye kanaler ikke nødvendigvis nedbringer ekspeditionstiden for nogle borgere,
eksempelvis borgere, der ikke kan benytte selvbetjeningsløsningen, og derfor
kræver en gennemgang af borgerservice personalet.

** Obligatoriske opgaver

Registranter har fået en rutine i at indmelde henvendelser, hvilket gør det
nødvendigt at formidle ændringerne i de nye procedurer. Det er derfor vigtigt
at formidle til medarbejdere, der skal aflære rutiner, før de kan lære de nye.

Til forskel fra første version af KOMHEN skal ALLE eksterne henvendelser registreres,
ikke kun til og fra borgere.

** Fejlhenvendelser
Fejlhenvendelser bør registreres, fordi det er vigtigt at vide om det eksisterende
kanalsystem er effektivt til at filtrere fejlhenvendelser frem.

** Generelt om henvendelser
- Ved hver indgående henvendelse, spørg borgeren om de har forsøgt at finde information
  på selvbetjening eller hjemmesiden.
- Og spørg hvilken information, borgeren rent faktisk kunne bruge til den konkrete
  henvendelse
- Ovenstående kan anskue effekten af de indledende informations- og selvbetjeningskanaler.  


* Præsentation

** Siden sidst
- Kort gennemgang af evalueringen for sidste uges tælleuge
- Kort gennemgang af nuværende niveau i opnåelse af den overordnede
  kanalstrategi
- Lille spørgerunde om de enhedsansvarliges, og opfattelsen af deres 
  medarbejderes, nuværende holdning til tælleugen.
** Overvejelser om præsentationen

- Overvej den specifikke opgaveabstraktion, du vil benytte i præsentationen
  til de enhedsansvarlige
  - Sørg for at give en ramme til at kategorisere henvendelser, men
    gå ikke ind i fagspecifikke opgavetyper. Det har du ikke nok viden til
  - Sørg i stedet for at få den enhedsansvarlige til prøve kræfter med at 
    kategorisere henvendelser i forhold til de udstikkede rammer.

** Henvendelsestests
Evalueringen har vist at visse medarbejdere er i tvivl om, hvordan henvendelserne
skal kategoriseres.
Forslag:
Træningsmateriale:
- Introduktion og gennemgang af 
